title: Victor Isakov
logo: https://avatars.githubusercontent.com/u/160557583?s=400&u=bdac60f5704b64d7e0ce8bdd97aad8d3d8f16ede&v=4
description: Data Science Portfolio
show_downloads: false
theme: jekyll-theme-hacker
linkedin_username: victor-isakov
email: vitek.isakov@icloud.com
custom_email: vitek.isakov@icloud.com
custom_linkedin: https://www.linkedin.com/in/victor-isakov
