title: Victor Isakov
logo: https://avatars.githubusercontent.com/u/160557583?s=400&u=bdac60f5704b64d7e0ce8bdd97aad8d3d8f16ede&v=4
description: Data Science Portfolio
show_downloads: false
linkedin_username: victor-isakov
email: vitek.isakov@icloud.com
theme: jekyll-theme-minimal
